name: grader test
on:
  workflow_dispatch:
  push:

jobs:
  template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: grade submission
        continue-on-error: true
        shell: bash
        run: |
          python -m grader assmt_simpleTasks/template --tests assmt_simpleTasks/tests --output scores.csv --log grader.log
      - name: upload results
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: ${{ github.workspace }}